name: tracking_cost
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State & core
  provider: ^6.1.2
  intl: ^0.20.2
  uuid: ^4.4.0

  # Location & permissions
  location: ^6.0.2
  permission_handler: ^11.3.1
  geolocator: ^14.0.0

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  fl_chart: ^1.0.0
  numberpicker: ^2.1.2

  # Files
  csv: ^6.0.0
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # codegen
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

# App icon
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.webp"
  min_sdk_android: 21

# Splash
flutter_native_splash:
  color: "#121212"
  color_dark: "#121212"
  image: assets/logo.jpg
  image_dark: assets/logo.jpg
  android_12:
    color: "#121212"
    color_dark: "#121212"
    image: assets/logo.jpg
    image_dark: assets/logo.jpg
